### ISSUE TITLE
[Feature] Ability to select layout at content creation time

### ISSUE THREAD

**Issue by wizhippo** [netgen-layouts/layouts-ezplatform#4]
It would be very convenient to be able to select the layout at the time of creating content without having to go into the layout admin and mapping the content to the correct layout.

**Comment by emodric** [comment]
That could be done. It would be a highly specialized solution only available in eZ Platform admin. Do you have any solution on how it could be done? Some kind of after publish redirect with signal slot? How would you control if you want the redirect or not after publish?

**Comment by emodric** [comment]
Closing as this is provided as part of a layout/mapping creation wizard in "Netgen Layouts" tab in eZ/Ibexa admin.
