### ISSUE TITLE
content preview in Netgen Admin UI doesn't work

### ISSUE THREAD

**Issue by fwoldt** [netgen-layouts/layouts-ezplatform#8]
If you create a layout which relating to the current location of the displayed object
the preview is not shown correctly. All parts which relating to the current location are not shown.
It looks like that the preview not know the current location.

So all dynamic queries relating to the current location will not work correctly in preview :-(
At the moment the preview is useless, if you trying to generate general layouts.

Please fix that - Thank's

**Comment by emodric** [comment]
@fwoldt Released as part of [v1.1.4](https://github.com/netgen-layouts/layouts-ezplatform/releases/tag/1.1.4)

**Comment by emodric** [comment]
@fwoldt It would be great if you could test to see if there are any further issues.
